<?php
require_once 'config/koneksi.php';
$page_title = 'Beranda';

// Get statistics menggunakan VIEW
$stats = [];

// Total produk
$result = $conn->query("SELECT COUNT(*) as total FROM produk");
$stats['total_produk'] = $result->fetch_assoc()['total'];

// Total kategori
$result = $conn->query("SELECT COUNT(*) as total FROM kategori");
$stats['total_kategori'] = $result->fetch_assoc()['total'];

// Total stok
$result = $conn->query("SELECT SUM(stok) as total FROM produk");
$stats['total_stok'] = $result->fetch_assoc()['total'];

// Get kategori untuk filter
$kategori_result = $conn->query("SELECT * FROM kategori ORDER BY nama_kategori");

include 'includes/header.php';
?>

<!-- Hero Section -->
<section class="hero-section">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-8">
                <h1 class="fade-in">Panduan Lengkap<br><span style="color: #dcfce7;">Pestisida & Obat Tani</span></h1>
                <p class="subtitle fade-in">Database terlengkap pestisida, fungisida, herbisida, dan obat-obatan pertanian. Lengkap dengan fungsi, dosis, dan harga terkini.</p>
            </div>
        </div>
        
        <div class="row mt-4">
            <div class="col-md-4 mb-3">
                <div class="stats-card fade-in">
                    <i class="bi bi-box-seam"></i>
                    <h3><?php echo $stats['total_produk']; ?></h3>
                    <p>Total Produk</p>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <div class="stats-card fade-in" style="animation-delay: 0.1s;">
                    <i class="bi bi-tags"></i>
                    <h3><?php echo $stats['total_kategori']; ?></h3>
                    <p>Kategori</p>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <div class="stats-card fade-in" style="animation-delay: 0.2s;">
                    <i class="bi bi-stack"></i>
                    <h3><?php echo number_format($stats['total_stok']); ?></h3>
                    <p>Total Stok</p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Main Content -->
<div class="container">
    <!-- Search & Filter -->
    <div class="search-filter-section fade-in">
        <div class="row">
            <div class="col-lg-12 mb-3">
                <div class="search-box">
                    <i class="bi bi-search"></i>
                    <input type="text" 
                           id="searchInput" 
                           class="form-control" 
                           placeholder="Cari nama produk, merek, atau bahan aktif...">
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-12">
                <div class="d-flex align-items-center mb-2">
                    <i class="bi bi-funnel me-2 text-success"></i>
                    <strong>Filter:</strong>
                </div>
                <div class="filter-chips">
                    <button class="chip active" data-category="">
                        <i class="bi bi-grid"></i>
                        Semua
                    </button>
                    <?php while($kat = $kategori_result->fetch_assoc()): ?>
                    <button class="chip" data-category="<?php echo $kat['id_kategori']; ?>">
                        <i class="bi bi-tag"></i>
                        <?php echo $kat['nama_kategori']; ?>
                    </button>
                    <?php endwhile; ?>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Product Grid -->
    <div id="productContainer" class="product-grid">
        <!-- Products will be loaded here via JavaScript -->
    </div>
    
    <!-- Pagination -->
    <div class="pagination-wrapper" id="paginationContainer">
        <!-- Pagination will be generated by JavaScript -->
    </div>
</div>

<?php include 'includes/footer.php'; ?>
